# Generated by Django 4.2 on 2024-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_tgo_account',
            field=models.BooleanField(default=False, help_text='TGO Account is your personal_id'),
        ),
    ]
