# Generated by Django 4.2 on 2024-02-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='身分證字號'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='手機號碼'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_tgo_account',
            field=models.BooleanField(default=False, help_text='TGO 帳號即為身分證字號 (目前僅提供個人用戶，未來會開發企業帳號選項)', verbose_name='使用 TGO 帳號'),
        ),
    ]
