# Generated by Django 4.2 on 2024-01-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_use_tgo_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='use_tgo_account',
            field=models.BooleanField(default=False, help_text='TGO account is your personal ID'),
        ),
    ]
