# Generated by Django 4.2 on 2024-03-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options_user_buy_discount_ticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '使用者資訊', 'verbose_name_plural': '使用者資訊(請先編輯完再訂票)'},
        ),
        migrations.AlterField(
            model_name='user',
            name='buy_discount_ticket',
            field=models.BooleanField(default=True, help_text='本選項乃為不想放置真實身份證字號之使用者設計。若取消勾選且架上只有優惠票，便不會購入任何票券', verbose_name='可以購買優惠票'),
        ),
    ]
