# Generated by Django 4.2 on 2024-03-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options_alter_user_buy_discount_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='buy_discount_ticket',
            field=models.BooleanField(default=True, help_text='本選項乃為不想放置真實身份證字號之使用者設計。若取消勾選且架上只有優惠票，便不會購入任何票券', verbose_name='允許購買優惠票'),
        ),
    ]
