# Generated by Django 4.2 on 2024-02-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_uniq_email_remove_user_uniq_invite_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitecode',
            old_name='id',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Personal ID'),
        ),
    ]
