# Generated by Django 4.2 on 2024-02-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_id_invitecode_code_alter_user_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='user.invitecode'),
        ),
    ]
