# Generated by Django 4.2 on 2024-05-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_buy_discount_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remind_holiday',
            field=models.BooleanField(default=True, verbose_name='節日訂票提醒'),
        ),
    ]
