# Generated by Django 4.2 on 2024-05-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_remind_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remind_holiday',
            field=models.BooleanField(default=True, verbose_name='疏運節日訂票提醒'),
        ),
    ]
