# Use the official nginx base image
FROM nginx

# Copy the configuration file
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Copy the static files to the appropriate location
WORKDIR /src
COPY src/static /src/static
# Expose port 80 for HTTP traffic
EXPOSE 80

# Start nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
