FROM python:3.10.12-slim

WORKDIR /src

COPY ./src .

ADD requirements/local.txt /tmp/

RUN mkdir -p logs/ && \
    apt update && \
    apt install -y libpq5 procps cron vim && \
    pip install -r /tmp/local.txt && \
    rm -r /tmp/local.txt
    # (crontab -l 2>/dev/null; echo "* * * * * /src/jobs/health_check.sh >> /src/logs/cron.log 2>&1") | crontab -
