services:
  cache:
    image: redis:alpine
    ports:
      - "8684:6379"
  db:
    image: postgres:latest
    restart: always
    ports:
      - "8685:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    links:
      - "db:db"
      - "cache:cache"
    volumes:
      - ./src:/src
      - ./requirements:/requirements
    ports:
      - "8686:8000"
    command: bash -c "pip freeze > /requirements/live.txt && gunicorn --timeout=300 --workers=2 --threads=8 --keep-alive=60 src.wsgi:application"
    environment:
      DEPLOY: dev
