# Generated by Django 4.2 on 2024-01-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingrequest_thsr_ticket_id_thsrticket_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='passenger_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Yet'), (1, 'Pending'), (2, 'Processing'), (3, 'Completed'), (-1, 'Expired'), (-2, 'Deleted')], default=0),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status'], name='booking_boo_status_c40eaf_idx'),
        ),
    ]
