# Generated by Django 4.2 on 2024-01-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingrequest_passenger_ids_bookingrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='thsr_ticket_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
