# Generated by Django 4.2 on 2024-02-16 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_alter_bookingrequest_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'verbose_name_plural': '訂票表單(點擊 + Add 開始訂票)'},
        ),
        migrations.AlterModelOptions(
            name='thsrticket',
            options={'verbose_name_plural': '已完成訂位資訊'},
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='adult_num',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, verbose_name='全票'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='booking_method',
            field=models.PositiveSmallIntegerField(choices=[(0, '時間'), (1, '車次')], default=0, verbose_name='訂票方式'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='child_num',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='孩童票(6-11歲)'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='college_num',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='大學生票'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='刪除時間'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='depart_date',
            field=models.DateField(verbose_name='出發日期'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='depart_station',
            field=models.PositiveSmallIntegerField(choices=[(1, '南港'), (2, '台北'), (3, '板橋'), (4, '桃園'), (5, '新竹'), (6, '苗栗'), (7, '台中'), (8, '彰化'), (9, '雲林'), (10, '嘉義'), (11, '台南'), (12, '左營')], default=1, verbose_name='啟程站'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='dest_station',
            field=models.PositiveSmallIntegerField(choices=[(1, '南港'), (2, '台北'), (3, '板橋'), (4, '桃園'), (5, '新竹'), (6, '苗栗'), (7, '台中'), (8, '彰化'), (9, '雲林'), (10, '嘉義'), (11, '台南'), (12, '左營')], default=12, verbose_name='到達站'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='disabled_num',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='愛心票'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='earliest_depart_time',
            field=models.CharField(blank=True, choices=[('', ''), ('500A', '05:00'), ('530A', '05:30'), ('600A', '06:00'), ('630A', '06:30'), ('700A', '07:00'), ('730A', '07:30'), ('800A', '08:00'), ('830A', '08:30'), ('900A', '09:00'), ('930A', '09:30'), ('1000A', '10:00'), ('1030A', '10:30'), ('1100A', '11:00'), ('1130A', '11:30'), ('1200N', '12:00'), ('1230P', '12:30'), ('100P', '13:00'), ('130P', '13:30'), ('200P', '14:00'), ('230P', '14:30'), ('300P', '15:00'), ('330P', '15:30'), ('400P', '16:00'), ('430P', '16:30'), ('500P', '17:00'), ('530P', '17:30'), ('600P', '18:00'), ('630P', '18:30'), ('700P', '19:00'), ('730P', '19:30'), ('800P', '20:00'), ('830P', '20:30'), ('900P', '21:00'), ('930P', '21:30'), ('1000P', '22:00'), ('1030P', '22:30'), ('1100P', '23:00'), ('1130P', '23:30'), ('1201A', '23:59')], default='', help_text='若以時間訂票需選擇', max_length=10, verbose_name='最早出發時間'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='elder_num',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, verbose_name='敬老票(65+)'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='error_msg',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='錯誤訊息'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='latest_arrival_time',
            field=models.CharField(blank=True, choices=[('', ''), ('500A', '05:00'), ('530A', '05:30'), ('600A', '06:00'), ('630A', '06:30'), ('700A', '07:00'), ('730A', '07:30'), ('800A', '08:00'), ('830A', '08:30'), ('900A', '09:00'), ('930A', '09:30'), ('1000A', '10:00'), ('1030A', '10:30'), ('1100A', '11:00'), ('1130A', '11:30'), ('1200N', '12:00'), ('1230P', '12:30'), ('100P', '13:00'), ('130P', '13:30'), ('200P', '14:00'), ('230P', '14:30'), ('300P', '15:00'), ('330P', '15:30'), ('400P', '16:00'), ('430P', '16:30'), ('500P', '17:00'), ('530P', '17:30'), ('600P', '18:00'), ('630P', '18:30'), ('700P', '19:00'), ('730P', '19:30'), ('800P', '20:00'), ('830P', '20:30'), ('900P', '21:00'), ('930P', '21:30'), ('1000P', '22:00'), ('1030P', '22:30'), ('1100P', '23:00'), ('1130P', '23:30'), ('1201A', '23:59')], default='', help_text='若以時間訂票需選擇', max_length=10, verbose_name='最晚抵達時間'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='passenger_ids',
            field=models.JSONField(blank=True, default=list, help_text='僅供優惠票實名制使用，若只訂一張票或確定該時段沒有優惠則不須填寫，填寫格式為 ["A123456789", "B123456789"]', null=True, verbose_name='乘客身分證字號'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='seat_prefer',
            field=models.PositiveSmallIntegerField(choices=[(0, '無'), (1, '靠窗'), (2, '靠走道')], default=0, verbose_name='座位偏好'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '尚未進入排程'), (1, '訂購中'), (2, '已完成'), (-1, '已過期'), (-2, 'Deleted')], default=1, editable=False, verbose_name='購票狀態'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='thsr_ticket',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.thsrticket', verbose_name='訂位代號'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='train_id',
            field=models.CharField(blank=True, help_text='若以車次訂票需填寫', max_length=10, verbose_name='車次'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='type_of_trip',
            field=models.PositiveSmallIntegerField(choices=[(0, '單程'), (1, '來回')], default=0, help_text='來回票功能尚未開放，請選擇單程', verbose_name='單程/來回'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='user',
            field=models.ForeignKey(db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='使用者帳號'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='arrival_station',
            field=models.PositiveSmallIntegerField(choices=[(1, '南港'), (2, '台北'), (3, '板橋'), (4, '桃園'), (5, '新竹'), (6, '苗栗'), (7, '台中'), (8, '彰化'), (9, '雲林'), (10, '嘉義'), (11, '台南'), (12, '左營')], verbose_name='到達站'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='抵達時間'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='date',
            field=models.CharField(blank=True, max_length=10, verbose_name='乘車日期'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='depart_station',
            field=models.PositiveSmallIntegerField(choices=[(1, '南港'), (2, '台北'), (3, '板橋'), (4, '桃園'), (5, '新竹'), (6, '苗栗'), (7, '台中'), (8, '彰化'), (9, '雲林'), (10, '嘉義'), (11, '台南'), (12, '左營')], verbose_name='啟程站'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='depart_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='出發時間'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='payment_deadline',
            field=models.CharField(blank=True, max_length=10, verbose_name='付款期限'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='seat_num',
            field=models.CharField(blank=True, max_length=50, verbose_name='座位號碼'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='訂位代號'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='total_price',
            field=models.CharField(blank=True, max_length=10, verbose_name='總金額'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='train_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='車次'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
