# Generated by Django 4.2 on 2024-01-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_bookingrequest_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='booking_method',
            field=models.CharField(choices=[('radio31', 'Time'), ('radio33', 'Train No')], default='radio31', max_length=255),
        ),
    ]
