# Generated by Django 4.2 on 2024-01-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookingrequest_booking_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thsrticket',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='depart_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
