# Generated by Django 4.2 on 2024-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookingrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '尚未進入排程'), (1, '訂購中'), (2, '已完成'), (-1, '已過期'), (-2, 'Deleted')], default=1, editable=False, verbose_name='購票狀態'),
        ),
    ]
