# Generated by Django 4.2 on 2024-03-06 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0006_alter_bookingrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'verbose_name': '訂票表單', 'verbose_name_plural': '訂票表單(點擊 + 新增訂票排程)'},
        ),
        migrations.AlterModelOptions(
            name='thsrticket',
            options={'verbose_name': '已完成訂位', 'verbose_name_plural': '已完成訂位'},
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='error_msg',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='錯誤訊息(前一輪訂票失敗原因)'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='passenger_ids',
            field=models.JSONField(blank=True, default=list, help_text='僅供優惠票實名制使用，若只訂一張票或確定該時段沒有優惠則不須填寫，填寫格式為 ["A123456789", "B123456789"]', null=True, verbose_name='乘客身分證列表(折扣用)'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '尚未進入排程'), (1, '訂購中'), (2, '已完成'), (-1, '已過期')], default=1, editable=False, verbose_name='購票狀態'),
        ),
        migrations.AlterField(
            model_name='thsrticket',
            name='user',
            field=models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='使用者帳號'),
        ),
    ]
