# Generated by Django 4.2 on 2024-01-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_thsrticket_arrival_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingLog',
        ),
        migrations.DeleteModel(
            name='BookingQueue',
        ),
        migrations.DeleteModel(
            name='BookingResult',
        ),
    ]
