# Generated by Django 4.2 on 2024-01-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_delete_bookinglog_delete_bookingqueue_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookingrequest',
            name='booking_boo_status_c40eaf_idx',
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status', '-depart_date'], name='booking_boo_status_9e3d6f_idx'),
        ),
    ]
