# Generated by Django 4.2 on 2024-01-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_bookingrequest_booking_boo_status_c40eaf_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='thsr_ticket_id',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='thsr_ticket',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.thsrticket', verbose_name='THSR Ticket ID'),
        ),
    ]
