# Generated by Django 4.2 on 2024-09-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_bookingrequest_type_of_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='error_msg',
            field=models.CharField(blank=True, editable=False, max_length=512, verbose_name='錯誤訊息(前一輪訂票失敗原因)'),
        ),
    ]
