# Generated by Django 4.2 on 2024-01-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_bookingrequest_thsr_ticket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='thsr_ticket',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.thsrticket', verbose_name='THSR Ticket ID'),
        ),
    ]
