# Generated by Django 4.2 on 2024-01-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_bookingrequest_thsr_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='booking_method',
            field=models.CharField(choices=[(0, 'Time'), (1, 'Train No')], default=0, max_length=255),
        ),
    ]
