# Generated by Django 4.2 on 2024-01-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_bookingrequest_booking_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='booking_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Time'), (1, 'Train No')], default=0),
        ),
    ]
