# Generated by Django 4.2 on 2024-02-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_bookingrequest_booking_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='error_msg',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
