# Generated by Django 4.2 on 2024-02-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_bookingrequest_error_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='depart_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='passenger_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Yet'), (1, 'Pending'), (2, 'Processing'), (3, 'Completed'), (-1, 'Expired'), (-2, 'Deleted')], default=1),
        ),
    ]
