# Generated by Django 4.2 on 2024-02-09 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0014_alter_bookingrequest_depart_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookingrequest',
            name='booking_boo_user_em_d76ad1_idx',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='user_email',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
